# -*- coding: utf-8 -*-
"""bayesTheram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12wdinTh_y5t8pnKdDQaeroCJXUUn3jLn

1.There are 100 students in a class. Consider these facts:

5 boys have books

35 boys do not have books

20 girls have 

40 girls do not have books

  Find the probability of a student having book, given a boy using Bayes theorem.
"""

def prob(expect,total):
  return expect/total

def bayesTheorem(pbook, pBoys, pBoysbook):
    return (pbook * pBoysbook) / pBoys

"""**Calculate Probablity**"""

total=100
boys=40
girls=60
boysBook=5
girlsBook=20
pofbook=prob(25,100)
prob_boys_books=prob(5,25)
prob_boys=prob(40,100)
print(round((25/100)*(5/25)/(40/100),2))

print("probablity oh boys that having book: "+str(round(bayesTheorem(pofbook,prob_boys,prob_boys_books),2)))